modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="${mod_issue_tracker_url}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
credits="${mod_credits}"
logoFile="icon.png"
description='''${mod_description}'''

[[mixins]]
    config = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.0,7.0.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="[1.0.0,2.1.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="bits_n_bobs"
    type="required"
    versionRange="[2.2.0,)"
    ordering="AFTER"
    side="BOTH"
